import RPI.GPIO as GPIO
import time


def setAllFalse():
    GPIO.output(14, False)
    GPIO.output(4, False)
    GPIO.output(20, False)
    GPIO.output(10, False)
    GPIO.output(18, False)
    GPIO.output(15, False)
    GPIO.output(16, False)
    GPIO.output(12, False)
    GPIO.output(9, False)
    GPIO.output(11, False)
    GPIO.output(2, False)
    GPIO.output(3, False)


GPIO.setmode(GPIO.BCM)
# 1st sensors inputs
GPIO.setup(17, GPIO.IN)
GPIO.setup(21, GPIO.IN)
GPIO.setup(26, GPIO.IN)
GPIO.setup(19, GPIO.IN)
# 2nd sensors inputs
GPIO.setup(8, GPIO.IN)
GPIO.setup(25, GPIO.IN)
GPIO.setup(1, GPIO.IN)
GPIO.setup(7, GPIO.IN)

GPIO.setup(18, GPIO.OUT)
GPIO.setup(15, GPIO.OUT)
GPIO.setup(14, GPIO.OUT)
GPIO.setup(20, GPIO.OUT)
GPIO.setup(16, GPIO.OUT)
GPIO.setup(12, GPIO.OUT)
GPIO.setup(10, GPIO.OUT)
GPIO.setup(9, GPIO.OUT)
GPIO.setup(11, GPIO.OUT)
GPIO.setup(2, GPIO.OUT)
GPIO.setup(3, GPIO.OUT)
GPIO.setup(4, GPIO.OUT)


while True:
    # Lane 1 Lane 2 Lane 3 Lane 4
    if(GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 0 and GPIO.input(8) == 0 and GPIO.input(25) == 0 and GPIO.input(1) == 0 and GPIO.input(7) == 0):
        print("All lanes are more 2 Sensors")
        setAllFalse()
        GPIO.output(10, True)
        GPIO.output(20, True)
        GPIO.output(4, True)
        GPIO.output(14, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(11, True)
        GPIO.output(12, True)
        GPIO.output(18, True)
        GPIO.output(2, True)
        time.sleep(3)
    # Lane 1 Lane 2 Lane 3
    elif(GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 0 and GPIO.input(8) == 0 and GPIO.input(25) == 1 and GPIO.input(1) == 0 and GPIO.input(7) == 0):
        print("Lane 1 Lane 2 and Lane 3 Two Sensors All")
        # lane 4 1st sensor active
        setAllFalse()
        GPIO.output(4, True)
        GPIO.output(14, True)
        GPIO.output(10, True)
        GPIO.output(20, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(11, True)
        GPIO.output(12, True)
        GPIO.output(18, True)
        GPIO.output(2, True)
        time.sleep(3)
    elif(GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 1 and GPIO.input(8) == 0 and GPIO.input(25) == 1 and GPIO.input(1) == 0 and GPIO.input(7) == 0):
        print("Lane 1 Lane 2 and Lane 3 Two Sensors All")
        # lane 4 1st sensor inactive
        setAllFalse()
        GPIO.output(4, True)
        GPIO.output(14, True)
        GPIO.output(10, True)
        GPIO.output(16, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(11, True)
        GPIO.output(16, True)
        GPIO.output(18, True)
        GPIO.output(2, True)
        time.sleep(3)
    elif((GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 0 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 0 and GPIO.input(7) == 1)
         or (GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 0 and GPIO.input(8) == 0 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 0)):
        print("Lane 1 Lane 2 and Lane 3 Two Sensors Lane 1 or Lane 3")
        # lane 4 active
        setAllFalse()
        GPIO.output(4, True)
        GPIO.output(14, True)
        GPIO.output(10, True)
        GPIO.output(20, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(11, True)
        GPIO.output(12, True)
        GPIO.output(18, True)
        GPIO.output(2, True)
        time.sleep(3)
    elif(GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 0 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 0):
        print("Lane 1 Lane 2 and Lane 3 Two Sensors Lane 2")
        # lane 4 active
        setAllFalse()
        GPIO.output(11, True)
        GPIO.output(12, True)
        GPIO.output(18, True)
        GPIO.output(2, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(4, True)
        GPIO.output(14, True)
        GPIO.output(10, True)
        GPIO.output(20, True)
        time.sleep(3)
    elif((GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 1 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 0 and GPIO.input(7) == 1)
         or (GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 1 and GPIO.input(8) == 0 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 0)):
        print("Lane 1 Lane 2 and Lane 3 Two Sensors Lane 1 or Lane 3")
        # lane 4 inactive
        setAllFalse()
        GPIO.output(4, True)
        GPIO.output(14, True)
        GPIO.output(10, True)
        GPIO.output(16, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(11, True)
        GPIO.output(16, True)
        GPIO.output(18, True)
        GPIO.output(2, True)
        time.sleep(3)
    elif(GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 0 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 0):
        print("Lane 1 Lane 2 and Lane 3 Two Sensors Lane 2")
        setAllFalse()
        # lane 4 inactive
        GPIO.output(11, True)
        GPIO.output(16, True)
        GPIO.output(18, True)
        GPIO.output(2, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(4, True)
        GPIO.output(14, True)
        GPIO.output(10, True)
        GPIO.output(16, True)
        time.sleep(3)
    # Lane 2 Lane 3 Lane 4
    elif(GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 1 and GPIO.input(21) == 0 and GPIO.input(8) == 0 and GPIO.input(25) == 0 and GPIO.input(1) == 0 and GPIO.input(7) == 0):
        print("Lane 2 Lane 3 and Lane 4 Two Sensors All")
        # lane 1 inactive
        setAllFalse()
        GPIO.output(11, True)
        GPIO.output(12, True)
        GPIO.output(18, True)
        GPIO.output(3, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(10, True)
        GPIO.output(20, True)
        GPIO.output(3, True)
        GPIO.output(14, True)
        time.sleep(3)
    elif(GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 0 and GPIO.input(8) == 0 and GPIO.input(25) == 0 and GPIO.input(1) == 0 and GPIO.input(7) == 0):
        print("Lane 2 Lane 3 and Lane 4 Two Sensors All")
        # lane 1 active
        setAllFalse()
        GPIO.output(11, True)
        GPIO.output(12, True)
        GPIO.output(18, True)
        GPIO.output(2, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(10, True)
        GPIO.output(20, True)
        GPIO.output(4, True)
        GPIO.output(14, True)
        time.sleep(3)
    elif((GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 1 and GPIO.input(21) == 0 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 0)
         or (GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 1 and GPIO.input(21) == 0 and GPIO.input(8) == 0 and GPIO.input(25) == 0 and GPIO.input(1) == 1 and GPIO.input(7) == 1)):
        print("Lane 2 Lane 3 and Lane 4 Two Sensors Lane 2 or Lane 4")
        # lane 1 inactive
        setAllFalse()
        GPIO.output(11, True)
        GPIO.output(12, True)
        GPIO.output(18, True)
        GPIO.output(3, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(10, True)
        GPIO.output(20, True)
        GPIO.output(3, True)
        GPIO.output(14, True)
        time.sleep(3)
    elif(GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 1 and GPIO.input(21) == 0 and GPIO.input(8) == 0 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 1):
        print("Lane 2 Lane 3 and Lane 4 Two Sensors Lane 3 More")
        setAllFalse()
        # lane 1 inactive
        GPIO.output(10, True)
        GPIO.output(20, True)
        GPIO.output(3, True)
        GPIO.output(14, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(11, True)
        GPIO.output(12, True)
        GPIO.output(18, True)
        GPIO.output(3, True)
        time.sleep(3)
    elif((GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 0 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 0)
         or (GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 0 and GPIO.input(8) == 1 and GPIO.input(25) == 0 and GPIO.input(1) == 1 and GPIO.input(7) == 1)):
        print("Lane 2 Lane 3 and Lane 4 Two Sensors Lane 2 or Lane 4")
        # lane 1 active
        setAllFalse()
        GPIO.output(11, True)
        GPIO.output(12, True)
        GPIO.output(18, True)
        GPIO.output(2, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(10, True)
        GPIO.output(20, True)
        GPIO.output(4, True)
        GPIO.output(14, True)
        time.sleep(3)
    elif(GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 1 and GPIO.input(8) == 0 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 1):
        print("Lane 2 Lane 3 and Lane 4 Two Sensors Lane 3 More")
        setAllFalse()
        # lane 1 active
        GPIO.output(10, True)
        GPIO.output(20, True)
        GPIO.output(4, True)
        GPIO.output(14, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(11, True)
        GPIO.output(12, True)
        GPIO.output(18, True)
        GPIO.output(2, True)
        time.sleep(3)
    # Lane 3 Lane 4 Lane 1
    elif(GPIO.input(17) == 0 and GPIO.input(19) == 1 and GPIO.input(26) == 0 and GPIO.input(21) == 0 and GPIO.input(8) == 0 and GPIO.input(25) == 0 and GPIO.input(1) == 0 and GPIO.input(7) == 1):
        print("Lane 3 Lane 4 and Lane 1 Two Sensors All")
        # lane 2 inactive
        setAllFalse()
        GPIO.output(9, True)
        GPIO.output(20, True)
        GPIO.output(4, True)
        GPIO.output(14, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(9, True)
        GPIO.output(12, True)
        GPIO.output(18, True)
        GPIO.output(2, True)
        time.sleep(3)
    elif(GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 0 and GPIO.input(8) == 0 and GPIO.input(25) == 0 and GPIO.input(1) == 0 and GPIO.input(7) == 1):
        print("Lane 3 Lane 4 and Lane 1 Two Sensors All")
        # lane 2 active
        setAllFalse()
        GPIO.output(10, True)
        GPIO.output(20, True)
        GPIO.output(4, True)
        GPIO.output(14, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(11, True)
        GPIO.output(12, True)
        GPIO.output(18, True)
        GPIO.output(2, True)
        time.sleep(3)
    elif((GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 1 and GPIO.input(8) == 0 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 1)
         or (GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 1 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 0 and GPIO.input(7) == 1)):
        print("Lane 3 Lane 4 and Lane 1 Two Sensors Lane 1 or Lane 3")
        # lane 2 active
        setAllFalse()
        GPIO.output(10, True)
        GPIO.output(20, True)
        GPIO.output(4, True)
        GPIO.output(14, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(11, True)
        GPIO.output(12, True)
        GPIO.output(18, True)
        GPIO.output(2, True)
        time.sleep(3)
    elif(GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 1 and GPIO.input(8) == 1 and GPIO.input(25) == 0 and GPIO.input(1) == 1 and GPIO.input(7) == 1):
        print("Lane 3 Lane 4 and Lane 1 Two Sensors Lane 4 More")
        # lane 2 active
        setAllFalse()
        GPIO.output(11, True)
        GPIO.output(12, True)
        GPIO.output(18, True)
        GPIO.output(2, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(10, True)
        GPIO.output(20, True)
        GPIO.output(4, True)
        GPIO.output(14, True)
        time.sleep(3)
    elif((GPIO.input(17) == 0 and GPIO.input(19) == 1 and GPIO.input(26) == 0 and GPIO.input(21) == 1 and GPIO.input(8) == 0 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 1)
         or (GPIO.input(17) == 0 and GPIO.input(19) == 1 and GPIO.input(26) == 0 and GPIO.input(21) == 1 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 0 and GPIO.input(7) == 1)):
        print("Lane 3 Lane 4 and Lane 1 Two Sensors Lane 1 or Lane 3")
        # lane 2 inactive
        setAllFalse()
        GPIO.output(9, True)
        GPIO.output(20, True)
        GPIO.output(4, True)
        GPIO.output(14, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(9, True)
        GPIO.output(12, True)
        GPIO.output(18, True)
        GPIO.output(2, True)
        time.sleep(3)
    elif(GPIO.input(17) == 0 and GPIO.input(19) == 1 and GPIO.input(26) == 0 and GPIO.input(21) == 1 and GPIO.input(8) == 1 and GPIO.input(25) == 0 and GPIO.input(1) == 1 and GPIO.input(7) == 1):
        print("Lane 3 Lane 4 and Lane 1 Two Sensors Lane 4 More")
        # lane 2 inactive
        setAllFalse()
        GPIO.output(9, True)
        GPIO.output(12, True)
        GPIO.output(18, True)
        GPIO.output(2, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(9, True)
        GPIO.output(20, True)
        GPIO.output(4, True)
        GPIO.output(14, True)
        time.sleep(3)
    # Lane 4 Lane 1 Lane 2
    elif(GPIO.input(17) == 1 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 0 and GPIO.input(8) == 1 and GPIO.input(25) == 0 and GPIO.input(1) == 0 and GPIO.input(7) == 0):
        print("Lane 4 Lane 1 and Lane 2 Two Sensors All")
        # lane 3 inactive
        setAllFalse()
        GPIO.output(11, True)
        GPIO.output(12, True)
        GPIO.output(15, True)
        GPIO.output(2, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(10, True)
        GPIO.output(20, True)
        GPIO.output(4, True)
        GPIO.output(15, True)
        time.sleep(3)
    elif(GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 0 and GPIO.input(8) == 1 and GPIO.input(25) == 0 and GPIO.input(1) == 0 and GPIO.input(7) == 0):
        print("Lane 4 Lane 1 and Lane 2 Two Sensors All")
        # lane 3 active
        setAllFalse()
        GPIO.output(11, True)
        GPIO.output(12, True)
        GPIO.output(18, True)
        GPIO.output(2, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(10, True)
        GPIO.output(20, True)
        GPIO.output(4, True)
        GPIO.output(14, True)
        time.sleep(3)
    elif((GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 0 and GPIO.input(8) == 1 and GPIO.input(25) == 0 and GPIO.input(1) == 1 and GPIO.input(7) == 1)
         or (GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 0 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 0)):
        print("Lane 4 Lane 1 and Lane 2 Two Sensors Lane 4 or Lane 2")
        setAllFalse()
        # lane3 active
        GPIO.output(11, True)
        GPIO.output(12, True)
        GPIO.output(18, True)
        GPIO.output(2, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(10, True)
        GPIO.output(20, True)
        GPIO.output(4, True)
        GPIO.output(14, True)
        time.sleep(3)
    elif(GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 1 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 0 and GPIO.input(7) == 1):
        print("Lane 4 Lane 1 and Lane 2 Two Sensors Lane 1 More")
        # lane 3 active
        setAllFalse()
        GPIO.output(10, True)
        GPIO.output(20, True)
        GPIO.output(4, True)
        GPIO.output(14, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(11, True)
        GPIO.output(12, True)
        GPIO.output(18, True)
        GPIO.output(2, True)
        time.sleep(3)
    elif((GPIO.input(17) == 1 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 0 and GPIO.input(8) == 1 and GPIO.input(25) == 0 and GPIO.input(1) == 1 and GPIO.input(7) == 1)
         or (GPIO.input(17) == 1 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 0 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 0)):
        print("Lane 4 Lane 1 and Lane 2 Two Sensors Lane 4 or Lane 2")
        setAllFalse()
        # lane3 inactive
        GPIO.output(11, True)
        GPIO.output(12, True)
        GPIO.output(15, True)
        GPIO.output(2, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(10, True)
        GPIO.output(20, True)
        GPIO.output(4, True)
        GPIO.output(15, True)
        time.sleep(3)
    elif(GPIO.input(17) == 1 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 1 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 0 and GPIO.input(7) == 1):
        print("Lane 4 Lane 1 and Lane 2 Two Sensors Lane 1 More")
        # lane 3 inactive
        setAllFalse()
        GPIO.output(10, True)
        GPIO.output(20, True)
        GPIO.output(4, True)
        GPIO.output(15, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(11, True)
        GPIO.output(12, True)
        GPIO.output(15, True)
        GPIO.output(2, True)
        time.sleep(3)
    # 2 lanes
    elif(GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 0 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 0 and GPIO.input(7) == 0):
        print("Lane 1 and Lane 2 Two Sensors 2 active")
        # all lanes has vechiles
        setAllFalse()
        GPIO.output(14, True)
        GPIO.output(4, True)
        GPIO.output(10, True)
        GPIO.output(20, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(18, True)
        GPIO.output(12, True)
        GPIO.output(11, True)
        GPIO.output(2, True)
        time.sleep(3)
    elif(GPIO.input(17) == 1 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 1 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 0 and GPIO.input(7) == 0):
        print("Lane 1 and Lane 2 Two Sensors 2 active")
        # lane 3 lane 4 has no vechiles
        setAllFalse()
        GPIO.output(10, True)
        GPIO.output(4, True)
        GPIO.output(15, True)
        GPIO.output(26, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(2, True)
        GPIO.output(11, True)
        GPIO.output(15, True)
        GPIO.output(16, True)
        time.sleep(3)
    elif(GPIO.input(17) == 1 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 1 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 0 and GPIO.input(7) == 1):
        print("Lane 1 and Lane 2 Two Sensors L1 more")
        # no vechiles detected lane 3 and lane 4
        setAllFalse()
        GPIO.output(10, True)
        GPIO.output(4, True)
        GPIO.output(15, True)
        GPIO.output(16, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(2, True)
        GPIO.output(15, True)
        GPIO.output(11, True)
        GPIO.output(16, True)
        time.sleep(3)
    elif(GPIO.input(17) == 1 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 1 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 0):
        print("Lane 1 and Lane 2 Two Sensors L2 more")
        # no vechiles detected lane 3 and lane 4
        setAllFalse()
        GPIO.output(2, True)
        GPIO.output(11, True)
        GPIO.output(15, True)
        GPIO.output(16, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(4, True)
        GPIO.output(15, True)
        GPIO.output(10, True)
        GPIO.output(16, True)
        time.sleep(3)
    elif(GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 0 and GPIO.input(8) == 0 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 0):
        print("Lane 2 and Lane 3 Two Sensors All sensors")
        # all lanes has vechiles
        setAllFalse()
        GPIO.output(18, True)
        GPIO.output(12, True)
        GPIO.output(11, True)
        GPIO.output(2, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(14, True)
        GPIO.output(4, True)
        GPIO.output(10, True)
        GPIO.output(20, True)
        time.sleep(3)
    elif(GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 1 and GPIO.input(21) == 1 and GPIO.input(8) == 0 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 0):
        print("Lane 2 and Lane 3 Two Sensors All sensors")
        # lane 1 lane 4 has no vechiles
        setAllFalse()
        GPIO.output(11, True)
        GPIO.output(18, True)
        GPIO.output(16, True)
        GPIO.output(3, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(14, True)
        GPIO.output(10, True)
        GPIO.output(16, True)
        GPIO.output(3, True)
        time.sleep(3)
    elif(GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 1 and GPIO.input(21) == 1 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 0):
        print("Lane 2 and Lane 3 Two Sensors L2 more")
        # no vechiles in other lanes
        setAllFalse()
        GPIO.output(3, True)
        GPIO.output(16, True)
        GPIO.output(11, True)
        GPIO.output(18, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(3, True)
        GPIO.output(16, True)
        GPIO.output(10, True)
        GPIO.output(14, True)
        time.sleep(3)
    elif(GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 1 and GPIO.input(21) == 1 and GPIO.input(8) == 0 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 1):
        print("Lane 2 and Lane 3 Two Sensors L3 more")
        # no vechiles in other lanes
        setAllFalse()
        GPIO.output(3, True)
        GPIO.output(16, True)
        GPIO.output(14, True)
        GPIO.output(10, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(3, True)
        GPIO.output(16, True)
        GPIO.output(11, True)
        GPIO.output(18, True)
        time.sleep(3)
    elif(GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 0 and GPIO.input(8) == 0 and GPIO.input(25) == 0 and GPIO.input(1) == 1 and GPIO.input(7) == 1):
        print("Lane 3 and Lane 4 Two Sensors All sensors")
        # all 1st sensors are active
        setAllFalse()
        GPIO.output(11, True)
        GPIO.output(12, True)
        GPIO.output(18, True)
        GPIO.output(2, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(4, True)
        GPIO.output(14, True)
        GPIO.output(10, True)
        GPIO.output(20, True)
        time.sleep(3)
    elif(GPIO.input(17) == 0 and GPIO.input(19) == 1 and GPIO.input(26) == 1 and GPIO.input(21) == 0 and GPIO.input(8) == 0 and GPIO.input(25) == 0 and GPIO.input(1) == 1 and GPIO.input(7) == 1):
        print("Lane 3 and Lane 4 Two Sensors All sensors")
        # No 1st sensors are active lane 1 lane 2 no vechiles
        setAllFalse()
        GPIO.output(9, True)
        GPIO.output(12, True)
        GPIO.output(18, True)
        GPIO.output(3, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(9, True)
        GPIO.output(14, True)
        GPIO.output(3, True)
        GPIO.output(20, True)
        time.sleep(3)
    elif(GPIO.input(17) == 0 and GPIO.input(19) == 1 and GPIO.input(26) == 1 and GPIO.input(21) == 0 and GPIO.input(8) == 0 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 1):
        print("Lane 3 and Lane 4 Two Sensors Lane 3 More")
        # No 1st sensors are active
        setAllFalse()
        GPIO.output(3, True)
        GPIO.output(14, True)
        GPIO.output(20, True)
        GPIO.output(9, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(12, True)
        GPIO.output(18, True)
        GPIO.output(3, True)
        GPIO.output(9, True)
        time.sleep(3)
    elif(GPIO.input(17) == 0 and GPIO.input(19) == 1 and GPIO.input(26) == 1 and GPIO.input(21) == 0 and GPIO.input(8) == 0 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 1):
        print("Lane 3 and Lane 4 Two Sensors Lane 4 More")
        # No 1st sensors are active
        setAllFalse()
        GPIO.output(12, True)
        GPIO.output(18, True)
        GPIO.output(3, True)
        GPIO.output(9, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(3, True)
        GPIO.output(15, True)
        GPIO.output(20, True)
        GPIO.output(9, True)
        time.sleep(3)
    elif(GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) == 0 and GPIO.input(8) == 0 and GPIO.input(25) == 0 and GPIO.input(1) == 0 and GPIO.input(7) == 1):
        print("Lane 4 and Lane 1 Two Sensors Both sensors")
        # All 1st sensors are active
        setAllFalse()
        GPIO.output(14, True)
        GPIO.output(4, True)
        GPIO.output(10, True)
        GPIO.output(20, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(2, True)
        GPIO.output(18, True)
        GPIO.output(4, True)
        GPIO.output(14, True)
        time.sleep(3)
    elif(GPIO.input(17) == 1 and GPIO.input(19) == 1 and GPIO.input(26) == 0 and GPIO.input(21) == 0 and GPIO.input(8) == 1 and GPIO.input(25) == 0 and GPIO.input(1) == 0 and GPIO.input(7) == 1):
        print("Lane 4 and Lane 1 Two Sensors Both sensors")
        # No 1st sensors are active
        setAllFalse()
        GPIO.output(9, True)
        GPIO.output(15, True)
        GPIO.output(2, True)
        GPIO.output(12, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(9, True)
        GPIO.output(15, True)
        GPIO.output(4, True)
        GPIO.output(20, True)
        time.sleep(3)
    elif(GPIO.input(17) == 1 and GPIO.input(19) == 1 and GPIO.input(26) == 0 and GPIO.input(21) == 0 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 0 and GPIO.input(7) == 1):
        print("Lane 4 and Lane 1 Two Sensors L1 more")
        # No 1st sensors are active
        setAllFalse()
        GPIO.output(9, True)
        GPIO.output(15, True)
        GPIO.output(4, True)
        GPIO.output(20, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(9, True)
        GPIO.output(15, True)
        GPIO.output(2, True)
        GPIO.output(12, True)
        time.sleep(3)
    elif(GPIO.input(17) == 1 and GPIO.input(19) == 1 and GPIO.input(26) == 0 and GPIO.input(21) == 0 and GPIO.input(8) == 1 and GPIO.input(25) == 0 and GPIO.input(1) == 1 and GPIO.input(7) == 1):
        print("Lane 4 and Lane 1 Two Sensors L4 more")
        # No 1st sensors are active
        setAllFalse()
        GPIO.output(9, True)
        GPIO.output(15, True)
        GPIO.output(2, True)
        GPIO.output(12, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(9, True)
        GPIO.output(15, True)
        GPIO.output(4, True)
        GPIO.output(20, True)
        time.sleep(3)
    # 2 sensors... single lane
    elif(GPIO.input(17) != 0 and GPIO.input(19) != 0 and GPIO.input(26) == 0 and GPIO.input(21) != 0 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 0 and GPIO.input(7) == 1):
        print("Lane 1 Two Sensors")
        setAllFalse()
        GPIO.output(4, True)
        GPIO.output(16, True)
        GPIO.output(15, True)
        GPIO.output(9, True)
        time.sleep(3)
    elif(GPIO.input(17) != 0 and GPIO.input(19) == 0 and GPIO.input(26) != 0 and GPIO.input(21) != 0 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 0):
        print("Lane 2 Two Sensors")
        setAllFalse()
        GPIO.output(16, True)
        GPIO.output(15, True)
        GPIO.output(11, True)
        GPIO.output(3, True)
        time.sleep(3)
    elif(GPIO.input(17) == 0 and GPIO.input(19) != 0 and GPIO.input(26) != 0 and GPIO.input(21) != 0 and GPIO.input(8) == 0 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 1):
        print("Lane 3 Two Sensors")
        setAllFalse()
        GPIO.output(14, True)
        GPIO.output(16, True)
        GPIO.output(9, True)
        GPIO.output(3, True)
        time.sleep(3)
    elif(GPIO.input(17) != 0 and GPIO.input(19) != 0 and GPIO.input(26) != 0 and GPIO.input(21) == 0 and GPIO.input(8) == 1 and GPIO.input(25) == 0 and GPIO.input(1) == 1 and GPIO.input(7) == 1):
        print("Lane 4 Two Sensors")
        setAllFalse()
        GPIO.output(15, True)
        GPIO.output(12, True)
        GPIO.output(9, True)
        GPIO.output(3, True)
        time.sleep(3)
    if (GPIO.input(17) == 0 and GPIO.input(21) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 1):
        setAllFalse()
        GPIO.output(14, True)
        GPIO.output(4, True)
        GPIO.output(20, True)
        GPIO.output(10, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(11, True)
        GPIO.output(12, True)
        GPIO.output(18, True)
        GPIO.output(2, True)
        time.sleep(3)
        print("Object Detected in all lanes")
        time.sleep(0.1)
    elif(GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) != 0 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 1):
        setAllFalse()
        GPIO.output(14, True)
        GPIO.output(4, True)
        GPIO.output(16, True)
        GPIO.output(10, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(16, True)
        GPIO.output(11, True)
        print("Lane 1 and Lane 2 and lane 3")
        time.sleep(0.1)
    elif(GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) != 0 and GPIO.input(21) == 0 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 1):
        setAllFalse()
        GPIO.output(18, True)
        GPIO.output(12, True)
        GPIO.output(11, True)
        GPIO.output(3, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(14, True)
        GPIO.output(10, True)
        GPIO.output(20, True)
        GPIO.output(3, True)
        print("Lane 2 and Lane 3 and lane 4")
        time.sleep(0.1)
    elif(GPIO.input(17) == 0 and GPIO.input(19) != 0 and GPIO.input(26) == 0 and GPIO.input(21) == 0 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 1):
        setAllFalse()
        GPIO.output(14, True)
        GPIO.output(4, True)
        GPIO.output(20, True)
        GPIO.output(9, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(18, True)
        GPIO.output(12, True)
        GPIO.output(9, True)
        GPIO.output(2, True)
        print("Lane 3 and Lane 4 and lane 1")
        time.sleep(0.1)
    elif(GPIO.input(17) == 0 and GPIO.input(19) != 0 and GPIO.input(26) == 0 and GPIO.input(21) == 0 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 1):
        setAllFalse()
        GPIO.output(15, True)
        GPIO.output(12, True)
        GPIO.output(11, True)
        GPIO.output(2, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(4, True)
        GPIO.output(10, True)
        GPIO.output(15, True)
        GPIO.output(20, True)
        print("Lane 4 and Lane 1 and lane 2")
        time.sleep(0.1)
    # 2conditions
    elif(GPIO.input(17) != 0 and GPIO.input(19) == 0 and GPIO.input(26) == 0 and GPIO.input(21) != 0 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 1):
        print("Lane 1 and lane 2")
        setAllFalse()
        GPIO.output(4, True)
        GPIO.output(16, True)
        GPIO.output(10, True)
        GPIO.output(15, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(16, True)
        GPIO.output(15, True)
        GPIO.output(11, True)
        GPIO.output(2, True)
        time.sleep(3)
    elif(GPIO.input(19) != 0 and GPIO.input(17) == 0 and GPIO.input(26) == 0 and GPIO.input(21) != 0 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 1):
        print("Lane 1 and lane 3")
        setAllFalse()
        GPIO.output(14, True)
        GPIO.output(4, True)
        GPIO.output(16, True)
        GPIO.output(9, True)
        time.sleep(3)
    elif(GPIO.input(17) != 0 and GPIO.input(19) != 0 and GPIO.input(26) == 0 and GPIO.input(21) == 0 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 1):
        print("Lane 4 and Lane 1")
        setAllFalse()
        GPIO.output(4, True)
        GPIO.output(15, True)
        GPIO.output(20, True)
        GPIO.output(9, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(15, True)
        GPIO.output(12, True)
        GPIO.output(9, True)
        GPIO.output(2, True)
        time.sleep(3)
    elif(GPIO.input(17) == 0 and GPIO.input(19) == 0 and GPIO.input(26) != 0 and GPIO.input(21) != 0 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 1):
        print("Lane 3 and lane 2")
        setAllFalse()
        GPIO.output(16, True)
        GPIO.output(18, True)
        GPIO.output(11, True)
        GPIO.output(3, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(14, True)
        GPIO.output(16, True)
        GPIO.output(10, True)
        GPIO.output(3, True)
        time.sleep(3)
    elif(GPIO.input(17) != 0 and GPIO.input(19) == 0 and GPIO.input(26) != 0 and GPIO.input(21) == 0 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 1):
        print("Lane 4 and lane 2")
        setAllFalse()
        GPIO.output(15, True)
        GPIO.output(12, True)
        GPIO.output(11, True)
        GPIO.output(3, True)
        time.sleep(3)
    elif(GPIO.input(17) == 0 and GPIO.input(19) != 0 and GPIO.input(26) != 0 and GPIO.input(21) == 0 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 1):
        print("Lane 4 and lane 3")
        setAllFalse()
        GPIO.output(14, True)
        GPIO.output(20, True)
        GPIO.output(9, True)
        GPIO.output(3, True)
        time.sleep(3)
        setAllFalse()
        GPIO.output(18, True)
        GPIO.output(12, True)
        GPIO.output(9, True)
        GPIO.output(3, True)
        time.sleep(3)
    elif(GPIO.input(17) != 0 and GPIO.input(19) != 0 and GPIO.input(26) == 0 and GPIO.input(21) != 0 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 1):
        print("Lane 1")
        setAllFalse()
        GPIO.output(4, True)
        GPIO.output(16, True)
        GPIO.output(15, True)
        GPIO.output(9, True)
        time.sleep(3)
    elif(GPIO.input(17) != 0 and GPIO.input(19) == 0 and GPIO.input(26) != 0 and GPIO.input(21) != 0 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 1):
        print("Lane 2")
        setAllFalse()
        GPIO.output(16, True)
        GPIO.output(15, True)
        GPIO.output(11, True)
        GPIO.output(3, True)
        time.sleep(3)
    elif(GPIO.input(17) == 0 and GPIO.input(19) != 0 and GPIO.input(26) != 0 and GPIO.input(21) != 0 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 1):
        print("Lane 3")
        setAllFalse()
        GPIO.output(14, True)
        GPIO.output(16, True)
        GPIO.output(9, True)
        GPIO.output(3, True)
        time.sleep(3)
    elif(GPIO.input(17) != 0 and GPIO.input(19) != 0 and GPIO.input(26) != 0 and GPIO.input(21) == 0 and GPIO.input(8) == 1 and GPIO.input(25) == 1 and GPIO.input(1) == 1 and GPIO.input(7) == 1):
        print("Lane 4")
        setAllFalse()
        GPIO.output(15, True)
        GPIO.output(12, True)
        GPIO.output(9, True)
        GPIO.output(3, True)
        time.sleep(3)
    else:
        print("No vechile")
        GPIO.output(10, False)
        GPIO.output(9, True)
        GPIO.output(11, False)
        GPIO.output(15, True)
        GPIO.output(18, False)
        GPIO.output(14, False)
        GPIO.output(20, False)
        GPIO.output(16, True)
        GPIO.output(12, False)
        GPIO.output(2, False)
        GPIO.output(4, False)
        GPIO.output(3, True)
        time.sleep(0.1)
